### ISSUE TITLE
Some keyboard keys not recognized for keybinds while running with PROTON_ENABLE_WAYLAND=1 [The Finals]

### ISSUE THREAD

**Issue by CapoFantasma97** [CachyOS/proton-cachyos#63]
# Compatibility Report
- Name of the game with compatibility issues: The Finals
- Steam AppID of the game: 2073850

## System Information
- GPU: NVidia RTX 3070 Mobile
- Video driver version: 580.95.05
- Kernel version: 6.16.10-200.fc42.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/CapoFantasma97/39eddb8d3d120801c0af43ea04d9066d
- Proton version: proton-c achyos-10.0-20251006-slr-x86_64_v3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.
- [x] that I have verified the issue is present when using [Proton-CachyOS-SLR](https://github.com/CachyOS/proton-cachyos/releases) from this repository.
- [x] that I haven't encountered the issue using an official Proton, such as Proton, Proton Experimental or Proton Bleeding Edge.

## Symptoms 

When running the game with PROTON_ENABLE_WAYLAND=1, pretty much any keybind that contains anything different than a plain letter or number (e.g. accent letters, symbols and other things) appear blank. Trying to register them does nothing. While playing, those keybinds do not work, and registering a new key on the secondary slot of the keybinds makes them appear as the first key instead. Typing those keys in chat works fine, something with the way those keys are detected for the controls doesn't work. My keyboard is using the Italian layout.

Removing the launch option and running the game again makes those keybinds show up again and work fine.

I am unable to attach logs either as file or on gist or alternatives. The file comes at a whopping 79.4MiB and almost a million rows.

## Reproduction

1. Register keybinds in game with keys like è ò à + (the ones on the right of P and L in the Italian layout)
2. On the default Proton settings they will work fine
3. Launch the game with PROTON_ENABLE_WAYLAND=1
4. The keybinds containing those keys will disappear from the settings page
5. Try registering one of those keys
6. It will interact as if you're not inputting anything
7. Try to confirm anyway and test the affected keybinds in game, including the one you tried to fix
8. Those keybinds will not work
9. Do note how inputting those keys in the chat will not bring any issues
10. Close the game, remove PROTON_ENABLE_WAYLAND=1, launch the game again
11. The keybinds will reapper and they will work fine

**Comment by loathingKernel** [comment]
You can always compress the file to upload it. We might need it in this case more than anything. `zstd -19` should compress enough to make it upload-able.

**Comment by loathingKernel** [comment]
Please generate a proton log using `PROTON_LOG="+waylanddrv,+key,+keyboard"` to get the most relevant information.

**Comment by loathingKernel** [comment]
On the other hand OW2 seems to be working

[steam-2357570.log.zst.txt](https://github.com/user-attachments/files/22874305/steam-2357570.log.zst.txt)

**Comment by NelloKudo** [comment]
Tested also on McOsu and Persona 4 Golden:

[steam-607260.log.zst.txt](https://github.com/user-attachments/files/22874370/steam-607260.log.zst.txt) <- McOsu
[steam-1113000.log.zst.txt](https://github.com/user-attachments/files/22874373/steam-1113000.log.zst.txt) <- P4G

In the first, Italian characters work in chatboxes and also get detected correctly when setting shorcuts (e.g. `è` is detected as `egrave`) and the keybind works as expected.

In the second example instead, when settings shortcuts,  `è` is shown as `[`, that is none other than the replacement of è in the US layout. However, despite that, pressing the keybind still works as expected.

I'll test The Finals tomorrow, but pressing the actual keybind seems to always work in most games.

**Comment by CapoFantasma97** [comment]
> Please generate a proton log using `PROTON_LOG="+waylanddrv,+key,+keyboard"` to get the most relevant information.

It still produced a 65MiB file. I didn't know about compression tools and how to use them, I just checked zstd as you mentioned and I managed to make significantly smaller archive, but file type .zst not supported on GitHub.

So I guess I'll just upload it on a temporary host for now https://transfer.it/t/LIX051tTzDpD

Edit: 

[steam-2073850.log.zst.txt](https://github.com/user-attachments/files/22874582/steam-2073850.log.zst.txt)

**Comment by loathingKernel** [comment]
This should be fixed more or less. I will keep it open for now until I completely sync with Proto-EM-10.0-33. Latest version is missing a couple of commits.

**Comment by cprin21** [comment]
Commenting that this is indeed still a problem on the Jan 1st release.
